coverage:
  precision: 0
  round: down
  status:
    patch:
      default:
        target: 63
    project:
      default:
        threshold: 1%
    changes: false
#comment: false
ignore:
  - "tests/"
  - "pipert/contrib/"
  - "pipert/utils/"
  - "docs/"